---

driver:
  name: ec2
  region: eu-west-1
  require_chef_omnibus: false
  instance_type: t2.micro
  associate_public_ip: true

transport:
  # Looks like this is still a issue: https://github.com/test-kitchen/test-kitchen/issues/1035
  max_ssh_sessions: 5

provisioner:
  name: ansible_playbook
  hosts: test-kitchen
  require_chef_for_busser: false
  require_ruby_for_busser: false
  ansible_verbose: true
  ansible_verbosity: 2
  requirements_path: requirements.yml

verifier:
  name: inspec

platforms:
  - name: centos-7

suites:
  - name: default
